# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: xenial
latex: false
fortran: false
pandoc: false

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
  - export PATH=~/.cargo/bin:$PATH

after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - libsodium-dev
